name: DCO Check

on:
  pull_request:

permissions: {}

jobs:
  dco:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: DCO Check
        uses: KineticCafe/actions-dco@v3.2.0